name: Create Tag/Release
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  workflow_dispatch:
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }} # Required: the default workflow user does NOT trigger downstream actions
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Verify NPM token is valid
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami --registry https://registry.npmjs.org/
      - run: git config user.name "$GITHUB_ACTOR"
      - run: git config user.email ""
      - run: npm version patch
      - run: git push --all
      - run: git push --tags
